#ifndef H_FOO
#define H_FOO
float plo(
        char figure[10],
        float x1,
        float y1,
        float x2,
        float y2,
        float x3,
        float y3,
        float x4,
        float y4);
float per(
        char figure[10],
        float x1,
        float y1,
        float x2,
        float y2,
        float x3,
        float y3,
        float x4,
        float y4);
int peres(
        int k,
        float x1,
        float y1,
        float r1,
        float x2,
        float y2,
        float r2,
        float y22,
        float x3,
        float y3);
#endif
